config/routes.rb
Walko::Application.routes.draw do

  get "valoracion/get"
  get "valoracion/send"
  get "busqueda/new"
  get "busqueda/index"

  get "ldi/:id_ldi/comentario" => "comentario#new"
  post "ldi/:id_ldi/comentario" => "comentario#create"
  get "ldi/:id_ldi/comentario/edit/:id_com" => "comentario#edit"
  patch "ldi/:id_ldi/comentario/edit/:id_com" => "comentario#update"
  delete "ldi/:id_ldi/comentario/delete/:id_com" => "comentario#destroy"

  get "ldi/new" => "ldi#new"
  post "ldi/new" => "ldi#create"
  get "ldi/edit/:id" => "ldi#edit"
  patch "ldi/edit/:id" => "ldi#update"
  delete "ldi/delete/:id" => "ldi#destroy"

  get "poblacion/:id" => "poblacion#show"
  devise_for :usuarios

  get "valoracion/:ldi_id" => "valoracion#get"
  post "valoracion/:ldi_id" => "valoracion#send"

  root 'busqueda#new'

end

app/views/layouts/_header.html.haml
%nav{:class => "navbar navbar-default", :role =>"navigation"}
  .container-fluid
    /Brand and toggle get grouped for better mobile display
    .col-lg-2.col-xs-1
    .col-lg-2.navbar-header
      %button{:class => "navbar-toggle", "data-toggle" => "collapse", "data-target" => "#navbar-collapse"}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .logo
        = link_to root_url do
          = image_tag 'logo_multideg.png', :size => "120x32"

    /Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse.navbar-right#navbar-collapse
      %ul.nav.navbar-nav
        - if usuario_signed_in?
          %li.text-center
            = link_to :controller => "/ldi", :action => "new" do
              Recomendar lugar
          %li.divider.nav-divider
          %li.active.text-center
            = link_to :edit_usuario_registration do
              = current_usuario.nombre.upcase
          %li.text-center
            = link_to :destroy_usuario_session, :method => 'DELETE' do
              Salir
        - else
          %li.active.text-center
            = link_to :new_usuario_session do
              Entrar
          %li.text-center
            = link_to :new_usuario_registration do
              Registrar

app/views/layouts/_header_inicio.html.haml
%nav{:class => "navbar navbar-default", :id => "nav_inicio", :role =>"navigation"}
  .container-fluid
    /Brand and toggle get grouped for better mobile display
    .col-lg-2.col-xs-1
    .col-lg-2.navbar-header
      %button{:class => "navbar-toggle", "data-toggle" => "collapse", "data-target" => "#navbar-collapse"}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    /Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse.navbar-right#navbar-collapse
      %ul.nav.navbar-nav
        - if usuario_signed_in?
          %li.text-center
            = link_to :controller => "/ldi", :action => "new" do
              Recomendar lugar
          %li.divider.nav-divider
          %li.active.text-center
            = link_to :edit_usuario_registration do
              = current_usuario.nombre.upcase
          %li.text-center
            = link_to :destroy_usuario_session, :method => 'DELETE' do
              Salir
        - else
          %li.active.text-center
            = link_to :new_usuario_session do
              Entrar
          %li.text-center
            = link_to :new_usuario_registration do
              Registrar

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      walko
    =stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    =javascript_include_tag "application", "data-turbolinks-track" => true
    =javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"
    =javascript_include_tag "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"
    =javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyCMD38S0lcCVScKB_VHKDN5CjTYPih6l2Q&sensor=false"
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, user-scalable=no"}
    =csrf_meta_tags

  %body
    - if (current_page?(root_url) || current_page?(:busqueda_new))
      =render :partial => "layouts/header_inicio"
    - else
      =render :partial => "layouts/header"

    =yield